CREATE TABLE history (
	customer_ID VARCHAR,
	shopping_pt VARCHAR,
	record_type VARCHAR,
	day VARCHAR,
	time VARCHAR,
	state VARCHAR,
	location VARCHAR,
	group_size Integer,
	homeowner VARCHAR,
	car_age Integer,
	car_value VARCHAR,
	risk_factor VARCHAR,
	age_oldest Integer,
	age_youngest Integer,
	married_couple VARCHAR,
	c_previous VARCHAR,
	duration_previous Integer,
	A VARCHAR,
	B VARCHAR,
	C VARCHAR,
	D VARCHAR,
	E VARCHAR,
	F VARCHAR,
	G VARCHAR,
	cost Integer
);

CREATE TABLE grouped (
	customer_ID VARCHAR,
	state VARCHAR,
	location VARCHAR,
	group_size Integer,
	homeowner VARCHAR,
	car_age Integer,
	car_value VARCHAR,
	risk_factor VARCHAR,
	age_oldest Integer,
	age_youngest Integer,
	married_couple VARCHAR,
	c_previous VARCHAR,
	duration_previous Integer,
	isSingle_state BOOLEAN,
	isSingle_location BOOLEAN,
	isSingle_group_size BOOLEAN,
	isSingle_homeowner BOOLEAN,
	isSingle_car_age BOOLEAN,
	isSingle_car_value BOOLEAN,
	isSingle_risk_factor BOOLEAN,
	isSingle_age_oldest BOOLEAN,
	isSingle_age_youngest BOOLEAN,
	isSingle_married_couple BOOLEAN,
	isSingle_c_previous BOOLEAN,
	isSingle_duration_previous BOOLEAN
);